version: '3.1'

services:
  mysql:
    image: mysql:8.1
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mall_demo
      MYSQL_USER: asus
      MYSQL_PASSWORD: 123456
    volumes:
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    environment:
      REDIS_PASSWORD: 123456
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
